ex5.1_this_is_the_way
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-racheldekel pull request #1
Opened 2022-03-20 14:13 UTC by racheldekel

2022-03-24 04:08 UTC, talbarfm requested changes

2022-03-24 04:08 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +    print_deep_folder()
Add a new line at eof (end of file)

2022-03-24 04:08 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +def print_deep_folder():
I dont the the folder is deep - pick a better name

2022-03-24 04:08 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +def print_deep_folder():
function documentation should look like this -
![Capture](https://user-images.githubusercontent.com/13467749/159840350-74d1ada2-17b6-43c2-94e8-9fbb13308117.JPG)

2022-03-24 04:08 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +    only_deep = [f for f in directory_list if f.startswith("deep")]
dont use single parameter names

2022-03-24 04:08 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +    folder_path = input(INPUT_FOLDER_MESSAGE)
receive this as a function parameter and access a constant from the outside - it makes you code coupled with a specific path

2022-03-25 07:02 UTC, talbarfm reviewed
This ia duplicate pull request - use the comments here and close it

2022-03-31 07:20 UTC, lovodkin93 approved these changes
@racheldekel good job!

2022-03-31 13:31 UTC, closed without merging