Ex5.2 piece of cake
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-racheldekel pull request #3
Opened 2022-03-20 21:21 UTC by racheldekel

2022-03-22 17:32 UTC, talbarfm requested changes

2022-03-22 17:32 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +import os
Add a newline after imports

2022-03-22 17:32 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +INPUT_FOLDER_MESSAGE="insert the path to the folder:"
Start messages to the user with a capital letter

2022-03-22 17:32 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +# function that print the file in folder that start with "deep"
![Capture](https://user-images.githubusercontent.com/13467749/159539679-2db1201c-867e-464d-bec4-7f860f4722e5.JPG)
that's the standard format of python documentation  - use it

2022-03-22 17:32 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +    folder_path = input(INPUT_FOLDER_MESSAGE)
Why export it to a const if you use it once? its more lines of code and makes the code less readable with no benefit

2022-03-22 17:32 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +    only_deep = [f for f in directory_list if f.startswith("deep")]
only_deep_what? I would name this variable deep_files

2022-03-22 17:32 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +    only_deep = [f for f in directory_list if f.startswith("deep")]
f is not a good variable name - change it

2022-03-22 17:32 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +    only_deep = [f for f in directory_list if f.startswith("deep")]
there are things other then files in a folder - remember that

2022-03-22 17:32 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +    print_deep_folder()
Add a newline at eof

2022-03-22 17:32 UTC, talbarfm commented on ex5.2_cup_of_join.py
> +    print(print_join([1,2],[8],[9,5,6],seperator='@'))
spaces after ,

2022-03-22 17:32 UTC, talbarfm commented on ex5.2_cup_of_join.py
> +    list_with= [cell for curr_list in lists for cell in curr_list + [seperator]][:-1]
cell is a bad variable name unless we are studying biology ;)

2022-03-22 17:32 UTC, talbarfm commented on ex5.2_cup_of_join.py
> +        return 'empty'
you should avoid returning different types from functions even though python allows it -  https://stackoverflow.com/questions/1839289/why-should-functions-always-return-the-same-type

2022-03-22 17:32 UTC, talbarfm commented on ex5.2_cup_of_join.py
> +    print(print_join([1,2],[8],[9,5,6],seperator='@'))
newline at eof

2022-03-22 17:32 UTC, talbarfm commented on ex5.2_piece_of_cake.py
> +            if key not in optionals:
reduce this to a oneline if

2022-03-22 17:32 UTC, talbarfm commented on ex5.2_piece_of_cake.py
> +    for key in prices.keys():
you can iterate over keys and values of a dictionary at once 
![image](https://user-images.githubusercontent.com/13467749/159540842-3e7c5c2f-03e3-4727-8644-94a95c4b2189.png)

2022-03-22 17:32 UTC, talbarfm commented on ex5.2_piece_of_cake.py
> +    print(get_recipe_price({'chocolate': 18, 'milk': 8}, chocolate=200, milk=100))
Add a newline at eof

2022-03-22 17:32 UTC, talbarfm commented on ex5.1_this_is_the_way.py
> +#print the program
you dont have to document this part

2022-03-24 13:34 UTC, racheldekel commented
fix

2022-03-31 07:19 UTC, lovodkin93 approved these changes
@racheldekel  good job! you can now merge the pull request.

2022-03-31 13:27 UTC, merged